name: cpp-linter

on: 
  pull_request:
    paths-ignore: "docs/** external/** assets/** .github/**"

jobs:
  cpp-linter:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          step-summary: true
          file-annotations: false
          files-changed-only: true
          tidy-review: false
          ignore: docs|assets|external|.github
          tidy-checks: '-*'
          version: '19'
          
      - name: Check linting results
        if: steps.linter.outputs.checks-failed > 0
        run: echo 'Linting check failed! Open action summary annotations for more details'; exit 1 
